name: chocolatine
on:
  push:
    branches:
      -"ga-ignore"
  pull_request:
    branches:
      -"ga-ignore"
  workflow_dispatch:

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DOP-200-PAR-2-1-chocolatine-sacha.topaloff.git" 
  EXECUTABLES: ""
  
jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
